#!/usr/bin/env python3

import sys
from inotify_simple import INotify, flags

if len(sys.argv) != 2:
    print('Usage: wait-for-no-more-writes <file-to-watch>')
    sys.exit(1)

seen_writes = False
inotify = INotify()
wd = inotify.add_watch(sys.argv[1], flags.MODIFY)
while True:
    events_processed = 0
    for event in inotify.read(timeout=2000):
        #print(event)
        seen_writes = True
        events_processed += 1
    if seen_writes and events_processed == 0:
        #print('done, bye')
        break


