#!/usr/bin/env python3

import sys
from inotify_simple import INotify, flags

if len(sys.argv) != 2:
    print('Usage: wait-for-no-more-writes <file-to-watch>')
    sys.exit(1)

event_timeout_ms = 2 * 1000
writes_timeout_ms = 5 * 60 * 1000
no_writes_for_ms = 0

seen_writes = False
inotify = INotify()
wd = inotify.add_watch(sys.argv[1], flags.MODIFY)
while True:
    events_processed = 0
    for event in inotify.read(timeout=event_timeout_ms):
        #print(event)
        seen_writes = True
        events_processed += 1
    if seen_writes and events_processed == 0:
        #print("Exiting after observing writes")
        break
    if not seen_writes:
        no_writes_for_ms += event_timeout_ms
        if no_writes_for_ms > writes_timeout_ms:
            break


